### ISSUE TITLE
SSO does not run correctly

### ISSUE THREAD

**Issue by SunkyeongLee** [484WIMF/whats-in-my-fridge#2]
I am having an issue of OAuth::Unauthorized error.

401 Authorization required.

I have pushed all works so far into a branch named 'workspace' so please let me know if you find where the issues are

**Comment by SunkyeongLee** [comment]
Apparently it is because I didn't setup the callback URL

**Comment by raphaelmnsu** [comment]
I saw the same issue with some possible solutions?
https://stackoverflow.com/questions/50560813/devise-oauth-twitter-oauthunauthorized-forbidden-403/50857912#50857912

**Comment by SunkyeongLee** [comment]
Thank you! :)

**Comment by taniahsnpr** [comment]
I saw this right now and the person having the issue could resolve the problem! 
https://github.com/arunagw/omniauth-twitter/issues/128

**Comment by SunkyeongLee** [comment]
http://railscasts.com/episodes/241-simple-omniauth-revised
https://github.com/arunagw/omniauth-twitter
