### ISSUE TITLE
My app doesn't run correctly

### ISSUE THREAD

**Issue by kianarmokhtari** [484WIMF/whats-in-my-fridge#5]
I am facing issues with this error

rails server -p 8080 -b 0.0.0.0: command not found

any help?

**Comment by SunkyeongLee** [comment]
@kianarmokhtari  Were you able to fix it?

**Comment by raphaelmnsu** [comment]
did you try to use this command to run your app? rails server -p $PORT -b $IP

**Comment by SunkyeongLee** [comment]
Yeah we tried that but none of her workspace worked. It worked like few hour ago but it stopped. We installed all necessary gems and everything but it didn't work

try
rails server -d
and see if it works.
